import type { PaletteColor, SlideTheme } from "@/types";

/**
 * Build a custom Marp CSS theme from the user's palette.
 * The theme overrides the base theme color variables so every
 * slide automatically adopts the user's brand colors.
 */
export function buildMarpTheme(
  palette: PaletteColor[],
  baseTheme: SlideTheme = "default"
): string {
  const get = (role: string, fallback = "#ffffff") =>
    palette.find((c) => c.role === role)?.hex ?? fallback;

  const primary = get("primary", "#344620");
  const secondary = get("secondary", "#2a3580");
  const accent = get("accent", "#d57a2a");
  const background = get("background", "#ffffff");
  const text = get("text", "#1a1a1a");
  const surface = get("surface", "#f8f9fa");
  const border = get("border", "#e2e8f0");

  const baseStyles = getBaseStyles(baseTheme, {
    primary,
    secondary,
    accent,
    background,
    text,
    surface,
    border,
  });

  return `/* @theme jedith-${baseTheme} */
/* Auto-generated by JEdithUI — ${new Date().toISOString()} */

:root {
  --color-primary: ${primary};
  --color-secondary: ${secondary};
  --color-accent: ${accent};
  --color-background: ${background};
  --color-text: ${text};
  --color-surface: ${surface};
  --color-border: ${border};
}

${baseStyles}
`;
}

function getBaseStyles(
  theme: SlideTheme,
  colors: Record<string, string>
): string {
  const { primary, secondary, accent, background, text, surface, border } =
    colors;

  switch (theme) {
    case "minimal":
      return `
section {
  background: ${background};
  color: ${text};
  font-family: 'Inter', 'Helvetica Neue', sans-serif;
  padding: 60px 80px;
}
section::after {
  font-size: 14px;
  color: ${border};
}
h1, h2, h3 {
  color: ${primary};
  border-bottom: 2px solid ${accent};
  padding-bottom: 8px;
}
a { color: ${accent}; }
code {
  background: ${surface};
  border: 1px solid ${border};
  border-radius: 4px;
  padding: 2px 6px;
}
pre {
  background: ${surface};
  border-left: 4px solid ${accent};
  padding: 16px;
  border-radius: 4px;
}
section.invert {
  background: ${primary};
  color: #ffffff;
}
section.invert h1, section.invert h2 {
  color: #ffffff;
  border-bottom-color: ${accent};
}
`;

    case "dark":
      return `
section {
  background: #1a1a2e;
  color: #e0e0e0;
  font-family: 'Inter', 'JetBrains Mono', monospace;
  padding: 60px 80px;
}
h1, h2, h3 {
  color: ${accent};
}
a { color: ${accent}; }
code, pre {
  background: #0f0f1a;
  color: ${accent};
  border-radius: 4px;
}
pre {
  border-left: 4px solid ${primary};
  padding: 16px;
}
section.title {
  background: linear-gradient(135deg, #1a1a2e 0%, ${primary} 100%);
  color: #ffffff;
}
`;

    case "tech":
      return `
section {
  background: ${background};
  color: ${text};
  font-family: 'JetBrains Mono', 'Fira Code', monospace;
  padding: 60px 80px;
  border-top: 4px solid ${accent};
}
h1, h2, h3 {
  color: ${primary};
  font-weight: 700;
}
h1 { font-size: 2.5em; border-left: 6px solid ${accent}; padding-left: 16px; }
a { color: ${accent}; }
code {
  background: ${primary}20;
  border: 1px solid ${primary}40;
  color: ${primary};
  border-radius: 3px;
  padding: 2px 4px;
}
pre {
  background: #0f111a;
  color: #e0e0e0;
  border-radius: 8px;
  padding: 20px;
}
`;

    case "colorful":
      return `
section {
  background: ${background};
  color: ${text};
  font-family: 'Inter', sans-serif;
  padding: 60px 80px;
}
h1 { color: ${primary}; }
h2 { color: ${secondary}; }
h3 { color: ${accent}; }
a { color: ${accent}; }
strong { color: ${accent}; }
section.title {
  background: linear-gradient(135deg, ${primary} 0%, ${secondary} 50%, ${accent} 100%);
  color: #ffffff;
}
section.title h1 { color: #ffffff; font-size: 3em; }
code {
  background: ${accent}15;
  color: ${accent};
  border-radius: 4px;
  padding: 2px 6px;
}
pre {
  background: ${primary}10;
  border-left: 4px solid ${accent};
  padding: 16px;
  border-radius: 4px;
}
`;

    case "gradient":
      return `
section {
  background: linear-gradient(160deg, ${background} 0%, ${surface} 100%);
  color: ${text};
  font-family: 'Inter', sans-serif;
  padding: 60px 80px;
}
h1, h2 { color: ${primary}; }
h1::after {
  content: '';
  display: block;
  width: 60px;
  height: 4px;
  background: linear-gradient(90deg, ${primary}, ${accent});
  margin-top: 8px;
  border-radius: 2px;
}
a { color: ${accent}; }
section.title {
  background: linear-gradient(135deg, ${primary} 0%, ${accent} 100%);
  color: #ffffff;
}
section.title h1 { color: #ffffff; }
section.title h1::after {
  background: rgba(255, 255, 255, 0.4);
}
`;

    case "business":
      return `
section {
  background: ${background};
  color: ${text};
  font-family: 'Georgia', 'Times New Roman', serif;
  padding: 60px 80px;
}
h1, h2, h3 {
  font-family: 'Inter', sans-serif;
  color: ${primary};
}
h1 {
  font-size: 2.4em;
  border-bottom: 3px double ${primary};
  padding-bottom: 12px;
}
a { color: ${accent}; text-decoration: underline; }
strong { color: ${primary}; }
table {
  border-collapse: collapse;
  width: 100%;
}
th {
  background: ${primary};
  color: #ffffff;
  padding: 8px 12px;
}
td {
  border-bottom: 1px solid ${border};
  padding: 8px 12px;
}
section.title {
  background: ${primary};
  color: #ffffff;
}
section.title h1 {
  color: #ffffff;
  border-bottom-color: ${accent};
}
`;

    default:
      return `
section {
  background: ${background};
  color: ${text};
  font-family: 'Inter', 'Helvetica Neue', sans-serif;
  padding: 60px 80px;
}
h1, h2, h3 { color: ${primary}; }
a { color: ${accent}; }
strong { color: ${accent}; }
code {
  background: ${surface};
  border: 1px solid ${border};
  border-radius: 4px;
  padding: 2px 6px;
  font-size: 0.9em;
}
pre {
  background: ${surface};
  border: 1px solid ${border};
  border-radius: 8px;
  padding: 20px;
}
table th { background: ${primary}; color: #ffffff; padding: 8px 12px; }
table td { border-bottom: 1px solid ${border}; padding: 8px 12px; }
section.title {
  background: ${primary};
  color: #ffffff;
}
section.title h1 { color: #ffffff; }
`;
  }
}
